IntersolarWeb/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

mysite/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.contrib.staticfiles import views
from django.conf import settings

urlpatterns = [
    url(r'^IntersolarWeb/', include('IntersolarWeb.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^static/(?P<path>.*)$', views.serve)]

IntersolarWeb/models.py
from __future__ import unicode_literals

from django.db import models

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

# Create your models here.

IntersolarWeb/forms.py
from django import forms

class DateForm(forms.Form):
    Date_from = forms.CharField(label='From', max_length=100)
    Date_to = forms.CharField(label='To', max_length=100)
    CHOICES= (('1','Thermal'),('2','Electrical'),)
    select = forms.ChoiceField(widget=forms.Select, choices=CHOICES)
    #Measurement = forms.CharField(label='Meas', max_length=100)
# your_name = forms.DateField(
#        widget=forms.DateInput(format=('%d-%m-%Y'), 
#                               attrs={'class':'myDateClass', 
#                               'placeholder':'Select a date'}))
#class MyForm(forms.Form):    
#    CHOICES= (('1','ME'),('2','YOU'),('3','WE'),)
#    select = forms.ChoiceField(widget=forms.Select, choices=CHOICES)
#    
#    							<select id="measurement_setup" name="measurement_setup" placeholder="large-4.columns">
#								<option value="1">Electrical</option><option value="2">Thermal</option> </select>

IntersolarWeb/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import DateForm
from django.http import HttpResponseRedirect
import Z_Data_Analysis_Django as da

x=30
y=20
z=x+y

import plotly
from plotly.graph_objs import Scatter, Layout

#For plotly, help: https://plot.ly/python/user-guide/
#https://plot.ly/python/getting-started/

#def index(request):
#    #return HttpResponse("Hello, world. You're at the polls index." + str(z))
#
##    template = loader.get_template('test.html')
##    context = {
##        'latest_question_list': latest_question_list,
##    }
##    return HttpResponse(template.render(context, request))
#    
#    return render(request, 'test.html', {'current_name':z})
    
    

def index(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = DateForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required. Returns true if  all the fields are valid. places the form in its cleaned data mode
            d_from=form.cleaned_data['Date_from']
            d_to=form.cleaned_data['Date_to']
            Meas=form.cleaned_data['select']
            print d_from
            
            if Meas=='1':
                df=da.Thermal(d_from,d_to)
            
                plotly.offline.plot({
                    "data": [Scatter(x=df.index, y=df['Mean Cavity'])],
                    "layout": Layout(title="Mean cavity temperature from "+d_from+" to "+d_to)
                },auto_open=False,filename='Thermal_graph.html')
            # ...
            # redirect to a new URL:
            #return HttpResponse(test2)
            #return HttpResponseRedirect('')
                return render(request, 'Thermal.html', {'form': form})
                
            if Meas=='2':
                df=da.Electrical(d_from,d_to)
            
                plotly.offline.plot({
                    "data": [Scatter(x=df.index, y=df['Pin[W]'])],
                    "layout": Layout(title="Power [W] from BIPV V0.3 from "+d_from+" to "+d_to)
                },auto_open=False,filename='Electrical_graph.html')
            # ...
            # redirect to a new URL:
            #return HttpResponse(test2)
            #return HttpResponseRedirect('')
                return render(request, 'Electrical.html', {'form': form})

    # if a GET (or any other method) we'll create a blank form
    else:
        form = DateForm()

        return render(request, 'Main.html', {'form': form})

templates/Electrical.html
<!doctype html>
{% load staticfiles %}
<html class="no-js" lang="en">
  <head>
  	<link rel="stylesheet" href="{% static 'css/foundation.css' %}">
	<link rel="stylesheet" href="{% static 'datetimepicker/jquery.datetimepicker.css' %}">
    <!--<link rel="stylesheet" type="text/css" href="datetimepicker/jquery.datetimepicker.css">-->
    <title>Energyville BIPV Web Application</title>
    
       
  </head>
  <body>

    <!-- Header and navigation -->
<div class="sticky">
	<nav class="top-bar" data-topbar role="navigation">
		<ul class="title-area">
			<li class="name">
				<h1><a href="#"><img src="{% static 'img/energyville.png' %}" style="height: 2.4rem;" alt="logo" />&nbsp;&nbsp;EnergyVille PVIV Web Application</a></h1>
			</li>
			<!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
			<li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
		</ul>
	</nav>
</div>  

			
    <!-- FROM, TO, UPDATE BUTTON AND MEASUREMENT SET UP -->   
    <div id="settings_div" class="row">
        
          <div class="large-12 columns">
                <h4>Settings</h4>
					<form action="/IntersolarWeb/" method="post">
						{% csrf_token %}
						<div class="large-3 columns">
						<label>From (UTC)</label>
						{{ form.Date_from }}
						</div>
						<div class="large-3 columns">
						<label>To (UTC)</label>
						{{ form.Date_to }}
						</div>
						<div class="large-3 columns">
						<label>Measurement</label>
						{{ form.select }}
						</div>						
						<div class="large-3 columns">
						<input type="submit" value="Submit" style="margin-top:18px; width: 100%;" class="small radius button"/>
						</div>			
					</form>
            </div>
    </div>
	
    <!-- Graph -->  
 	
	<div class="basic">
	
		{% include "C:/Users/Jonathan/Documents/Postdoc/Codes Python/Django website/mysite/Electrical_graph.html" %}    
	</div>

	
	<!-- Datetimepicker -->   

    <script src="{% static 'datetimepicker/jquery.js' %}"></script>
    <script src="{% static 'datetimepicker/jquery.datetimepicker.js' %}"></script>
    <script>
        // Datetime picker
        $('#id_Date_from').datetimepicker({
            mask:'9999/19/39 29:59:59',
            format:'Y/m/d H:i:s'
            //formatTime:'H:i'
        });
		
		$('#id_Date_to').datetimepicker({
            mask:'9999/19/39 29:59:59',
            format:'Y/m/d H:i:s'
            //formatTime:'H:i'
        });
    </script>


  </body>
</html>

templates/Main.html
<!doctype html>
{% load staticfiles %}
<html class="no-js" lang="en">
  <head>
  	<link rel="stylesheet" href="{% static 'css/foundation.css' %}">
	<link rel="stylesheet" href="{% static 'datetimepicker/jquery.datetimepicker.css' %}">
    <!--<link rel="stylesheet" type="text/css" href="datetimepicker/jquery.datetimepicker.css">-->
    <title>Energyville BIPV Web Application</title>
    
       
  </head>
  <body>

    <!-- Header and navigation -->
<div class="sticky">
	<nav class="top-bar" data-topbar role="navigation">
		<ul class="title-area">
			<li class="name">
				<h1><a href="#"><img src="{% static 'img/energyville.png' %}" style="height: 2.4rem;" alt="logo" />&nbsp;&nbsp;EnergyVille PVIV Web Application</a></h1>
			</li>
			<!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
			<li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
		</ul>
	</nav>
</div>  

			
    <!-- FROM, TO, UPDATE BUTTON AND MEASUREMENT SET UP -->   
    <div id="settings_div" class="row">
        
          <div class="large-12 columns">
                <h4>Settings</h4>
					<form action="/IntersolarWeb/" method="post">
						{% csrf_token %}
						<div class="large-3 columns">
						<label>From (UTC)</label>
						{{ form.Date_from }}
						</div>
						<div class="large-3 columns">
						<label>To (UTC)</label>
						{{ form.Date_to }}
						</div>
						<div class="large-3 columns">
						<label>Measurement</label>
						{{ form.select }}
						</div>						
						<div class="large-3 columns">
						<input type="submit" value="Submit" style="margin-top:18px; width: 100%;" class="small radius button"/>
						</div>			
					</form>
            </div>
    </div>
	
    <!-- Graph -->  

	
	<!-- Datetimepicker -->   

    <script src="{% static 'datetimepicker/jquery.js' %}"></script>
    <script src="{% static 'datetimepicker/jquery.datetimepicker.js' %}"></script>
    <script>
        // Datetime picker
        $('#id_Date_from').datetimepicker({
            mask:'9999/19/39 29:59:59',
            format:'Y/m/d H:i:s'
            //formatTime:'H:i'
        });
		
		$('#id_Date_to').datetimepicker({
            mask:'9999/19/39 29:59:59',
            format:'Y/m/d H:i:s'
            //formatTime:'H:i'
        });
    </script>


  </body>
</html>

templates/Thermal.html
<!doctype html>
{% load staticfiles %}
<html class="no-js" lang="en">
  <head>
  	<link rel="stylesheet" href="{% static 'css/foundation.css' %}">
	<link rel="stylesheet" href="{% static 'datetimepicker/jquery.datetimepicker.css' %}">
    <!--<link rel="stylesheet" type="text/css" href="datetimepicker/jquery.datetimepicker.css">-->
    <title>Energyville BIPV Web Application</title>
    
       
  </head>
  <body>

    <!-- Header and navigation -->
<div class="sticky">
	<nav class="top-bar" data-topbar role="navigation">
		<ul class="title-area">
			<li class="name">
				<h1><a href="#"><img src="{% static 'img/energyville.png' %}" style="height: 2.4rem;" alt="logo" />&nbsp;&nbsp;EnergyVille PVIV Web Application</a></h1>
			</li>
			<!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
			<li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
		</ul>
	</nav>
</div>  

			
    <!-- FROM, TO, UPDATE BUTTON AND MEASUREMENT SET UP -->   
    <div id="settings_div" class="row">
        
          <div class="large-12 columns">
                <h4>Settings</h4>
					<form action="/IntersolarWeb/" method="post">
						{% csrf_token %}
						<div class="large-3 columns">
						<label>From (UTC)</label>
						{{ form.Date_from }}
						</div>
						<div class="large-3 columns">
						<label>To (UTC)</label>
						{{ form.Date_to }}
						</div>
						<div class="large-3 columns">
						<label>Measurement</label>
						{{ form.select }}
						</div>						
						<div class="large-3 columns">
						<input type="submit" value="Submit" style="margin-top:18px; width: 100%;" class="small radius button"/>
						</div>			
					</form>
            </div>
    </div>
	
    <!-- Graph -->  
 	
	<div class="basic">
	
		{% include "C:/Users/Jonathan/Documents/Postdoc/Codes Python/Django website/mysite/Thermal_graph.html" %}    
	</div>

	
	<!-- Datetimepicker -->   

    <script src="{% static 'datetimepicker/jquery.js' %}"></script>
    <script src="{% static 'datetimepicker/jquery.datetimepicker.js' %}"></script>
    <script>
        // Datetime picker
        $('#id_Date_from').datetimepicker({
            mask:'9999/19/39 29:59:59',
            format:'Y/m/d H:i:s'
            //formatTime:'H:i'
        });
		
		$('#id_Date_to').datetimepicker({
            mask:'9999/19/39 29:59:59',
            format:'Y/m/d H:i:s'
            //formatTime:'H:i'
        });
    </script>


  </body>
</html>